# Generated by Django 4.0.1 on 2022-02-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplaylist',
            old_name='song',
            new_name='songs',
        ),
    ]
