# Generated by Django 4.0.1 on 2022-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_userplaylist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='background_color',
            field=models.CharField(blank=True, help_text='Background color for the playlist in hexadecimal', max_length=30, null=True),
        ),
    ]
