# Generated by Django 4.1 on 2022-09-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('background_color', models.CharField(blank=True, help_text='Background color for the playlist in hexadecimal', max_length=30, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user_sort', models.CharField(choices=[('Song name', 'Song Name'), ('Album name', 'Album Name'), ('Artist name', 'Artist Name'), ('Added', 'Added'), ('Duration', 'Duration'), ('Genre', 'Genre')], default='Album name', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='user_playlist_followers', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='artists.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('background_color', models.CharField(blank=True, help_text='Background color for the playlist in hexadecimal', max_length=30, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='official_playlist_followers', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, to='artists.song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
