# Generated by Django 4.1 on 2022-09-08 14:43

from django.db import migrations, models
import imagekit.models.fields
import playlists.utils


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialplaylist',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=playlists.utils.playlists_cover_image_path),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=playlists.utils.playlists_cover_image_path),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='user_sort',
            field=models.CharField(choices=[('Song name', 'Song Name'), ('Album name', 'Album Name'), ('Artist name', 'Artist Name'), ('Added', 'Added'), ('Duration', 'Duration'), ('Genre', 'Genre')], default='Album name', max_length=50),
        ),
    ]
