# Generated by Django 4.1.3 on 2023-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_userplaylist_user_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='user_sort',
            field=models.CharField(choices=[('Song name', 'Song Name'), ('Album name', 'Album Name'), ('Artist name', 'Artist Name'), ('Added', 'Added'), ('Duration', 'Duration'), ('Genre', 'Genre')], default='Album name', help_text='The sorting mechanism chosen by the user', max_length=50),
        ),
    ]
