# Generated by Django 4.1 on 2022-09-08 13:10

import artists.utils
import artists.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Bouyon', 'Bouyon'), ('Kompa', 'Kompa'), ('Dancehall', 'Dancehall'), ('Zouk', 'Zouk')], default='Dancehall', max_length=100)),
                ('cover_image', models.ImageField(upload_to=artists.utils.cover_image_path)),
                ('producer', models.CharField(max_length=100)),
                ('is_single', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('presentation', models.TextField(blank=True, max_length=1000, null=True)),
                ('area', models.CharField(choices=[('Guadeloupe', 'Guadeloupe'), ('Jamaica', 'Jamaica')], default='Jamaica', max_length=100)),
                ('nationality', models.CharField(choices=[('French', 'French'), ('Jamaican', 'Jamaican')], default='Jamaican', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, validators=[artists.validators.validate_date_of_birth])),
                ('genre', models.CharField(choices=[('Bouyon', 'Bouyon'), ('Kompa', 'Kompa'), ('Dancehall', 'Dancehall'), ('Zouk', 'Zouk')], default='Dancehall', max_length=100)),
                ('cover_image', models.ImageField(upload_to=artists.utils.artist_cover_image_path)),
                ('modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Song name', max_length=100)),
                ('song_file', models.FileField(upload_to=artists.utils.song_path, validators=[artists.validators.song_file_validator])),
                ('genre', models.CharField(choices=[('Bouyon', 'Bouyon'), ('Kompa', 'Kompa'), ('Dancehall', 'Dancehall'), ('Zouk', 'Zouk')], default='Dancehall', max_length=100)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('bitrate', models.PositiveIntegerField(default=0)),
                ('is_explicit', models.BooleanField(default=False)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.album')),
                ('featuring_artists', models.ManyToManyField(blank=True, help_text='Artists who have featured in the song', to='artists.artist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['name', 'genre', 'album'], name='artists_son_name_c71488_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name', 'genre'], name='artists_art_name_ed2fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'name', 'genre'], name='artists_alb_artist__1ac749_idx'),
        ),
    ]
