import { faMusic, faHome, faSearch, faList, faPlus, faPlay, faEllipsisVertical, faPause, faHeartCircleCheck, faHeartCircleMinus, faHeart, faCircleInfo, faE, faCirclePlus, faIcons, faMagnifyingGlass, faCog, faForwardStep, faBackwardStep, faVolumeUp, faRepeat, faChartSimple, faArrowLeft, faBell, faSort } from '@fortawesome/free-solid-svg-icons'
import { library } from '@fortawesome/fontawesome-svg-core'


library.add(faMusic)
library.add(faHome)
library.add(faSearch)
library.add(faList)
library.add(faPlus)
library.add(faPlay)
library.add(faPause)
library.add(faEllipsisVertical)
library.add(faHeart)
library.add(faHeartCircleCheck)
library.add(faHeartCircleMinus)
library.add(faCircleInfo)
library.add(faCirclePlus)
library.add(faIcons)
library.add(faE)
library.add(faMagnifyingGlass)
library.add(faCog)
library.add(faRepeat)
library.add(faForwardStep)
library.add(faBackwardStep)
library.add(faVolumeUp)
library.add(faSort)
library.add(faChartSimple)
library.add(faArrowLeft)
library.add(faBell)
